In [16]:
import numpy as np 
import pandas as pd 
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import tree


df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

print(df_train.shape)
print(df_test.shape)

(42000, 785)
(28000, 784)


In [17]:
X = []
y = []
for row in df_train.iterrows() :
    label = row[1][0] # label (the number visible in the image)
    image = list(row[1][1:]) # image information as list, without label
    image = np.array(image) / 255
    X.append(image)
    y.append(label)

X = np.array(X)
y = np.array(y)
print(len(X))
print(len(y))

42000
42000


In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
print(len(X_train), len(y_train))
print(X_train[1].shape)

28140 28140
(784,)


In [19]:
clf = tree.DecisionTreeClassifier(criterion="entropy")
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(y_pred[0:20], ".....")
print(y_test[0:20], ".....")
print(metrics.accuracy_score(y_test, y_pred))

[8 1 9 9 8 6 2 7 7 1 6 3 1 2 7 9 3 3 6 4] .....
[8 1 9 9 8 6 2 2 7 1 6 3 1 2 7 4 3 3 6 4] .....
0.8556998556998557


In [20]:
X_new = []
for row in df_test.iterrows() :
    image = list(row[1])
    image = np.array(image) / 255
    X_new.append(image)
X_new = np.array(X_new)
print(len(X_new))
print(len(df_test))

28000
28000


In [21]:
y_new_pred = clf.predict(X_new)
print(y_new_pred)

[2 0 9 ... 3 7 2]


In [3]:
clf = tree.DecisionTreeClassifier(criterion="gini")
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(y_pred[0:20], ".....")
print(y_test[0:20], ".....")
print(metrics.accuracy_score(y_test, y_pred))

[8 1 9 9 8 5 2 7 1 5 3 1 2 7 9 3 3 6 4] .....
[8 1 9 9 8 6 2 7 1 6 3 1 2 7 4 3 3 6 4] .....
0.881479641479642


In [23]:
X_new = []
for row in df_test.iterrows() :
    image = list(row[1])
    image = np.array(image) / 255
    X_new.append(image)
X_new = np.array(X_new)
print(len(X_new))
print(len(df_test))

28000
28000


In [24]:
y_new_pred = clf.predict(X_new)
print(y_new_pred)

[2 2 9 ... 3 9 2]


In [4]:
from c45 import C45

clf = C45()
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.005,test_size=0.01, random_state=42)
clf.fit(X_train, y_train)
print(f'Accuracy: {clf.score(X_test, y_test)}')

Accuracy: 0.866985656985656


In [26]:
X_new = []
for row in df_test.iterrows() :
    image = list(row[1])
    image = np.array(image) / 255
    X_new.append(image)
X_new = np.array(X_new)
print(len(X_new))
print(len(df_test))

28000
28000


In [27]:
y_new_pred = clf.predict(X_new)
print(y_new_pred)

[2, 0, 4, 4, 1, 0, 8, 3, 0, 3, 3, 2, 5, 0, 7, 0, 2, 1, 9, 0, 4, 1, 2, 2, 7, 9, 6, 7, 7, 7, 2, 7, 7, 1, 6, 7, 9, 4, 1, 0, 7, 7, 4, 9, 8, 7, 2, 8, 9, 2, 6, 8, 1, 3, 8, 6, 1, 2, 6, 4, 7, 2, 2, 7, 0, 8, 1, 7, 0, 1, 6, 8, 9, 8, 2, 0, 9, 3, 1, 1, 5, 9, 1, 0, 4, 1, 2, 3, 2, 7, 6, 6, 6, 6, 1, 1, 5, 4, 7, 0, 5, 9, 2, 0, 7, 2, 0, 5, 0, 7, 0, 8, 9, 2, 1, 2, 2, 1, 8, 2, 3, 7, 2, 1, 6, 3, 8, 7, 1, 5, 3, 8, 6, 0, 0, 0, 3, 1, 9, 0, 0, 2, 2, 5, 3, 2, 7, 7, 2, 8, 5, 3, 5, 6, 5, 2, 7, 9, 7, 1, 6, 0, 4, 5, 3, 5, 7, 2, 5, 0, 4, 7, 4, 6, 1, 6, 2, 4, 1, 2, 2, 1, 8, 6, 4, 9, 2, 1, 1, 8, 6, 1, 7, 9, 9, 0, 6, 7, 4, 7, 1, 9, 5, 9, 5, 0, 8, 4, 6, 2, 0, 3, 3, 6, 7, 2, 1, 6, 3, 4, 2, 3, 3, 4, 2, 8, 3, 0, 1, 0, 0, 2, 9, 1, 2, 1, 5, 1, 1, 6, 6, 6, 2, 8, 7, 5, 4, 6, 3, 4, 9, 7, 1, 3, 1, 7, 5, 1, 4, 9, 6, 0, 2, 5, 9, 0, 6, 9, 5, 1, 6, 0, 6, 3, 2, 0, 1, 9, 1, 4, 0, 5, 1, 0, 6, 3, 7, 1, 4, 7, 8, 7, 7, 9, 7, 0, 3, 5, 8, 8, 6, 7, 8, 2, 5, 2, 2, 1, 4, 5, 8, 9, 4, 0, 0, 3, 7, 4, 1, 4, 8, 1, 1, 3, 8, 0, 5, 1, 3, 2, 6, 3, 1, 