In [1]:
import numpy as np
def sigmoid (x):
    return 1/(1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

def mlp(inputs,expected_output,epochs=400,lr=0.25,inputLayerNeurons=2,hiddenLayerNeurons=2,outputLayerNeurons=1):
    hidden_weights = np.random.uniform(size=(inputLayerNeurons,hiddenLayerNeurons))
    hidden_bias =-1 *np.random.uniform(size=(1,hiddenLayerNeurons))
    output_weights = np.random.uniform(size=(hiddenLayerNeurons,outputLayerNeurons))
    output_bias =-1 *np.random.uniform(size=(1,outputLayerNeurons))
    print("Initial hidden weights: ",end='')
    print(*hidden_weights)
    print("Initial hidden biases: ",end='')
    print(*hidden_bias)
    print("Initial output weights: ",end='')
    print(*output_weights)
    print("Initial output biases: ",end='')
    print(*output_bias)
    
    for i in range(epochs):
        hidden_layer_activation = np.dot(inputs,hidden_weights)
        hidden_layer_activation += hidden_bias
        hidden_layer_output = sigmoid(hidden_layer_activation)

        output_layer_activation = np.dot(hidden_layer_output,output_weights)
        output_layer_activation += output_bias
        predicted_output = sigmoid(output_layer_activation)

        error = predicted_output-expected_output
        
        if i%100==0:
            print("Iteration:", i)
            print(error)
           
        d_predicted_output = error * sigmoid_derivative(predicted_output)

        error_hidden_layer = d_predicted_output.dot(output_weights.T)
        d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

        output_weights -= hidden_layer_output.T.dot(d_predicted_output) * lr
        output_bias -= np.sum(d_predicted_output,axis=0,keepdims=True) * lr
        hidden_weights -= inputs.T.dot(d_hidden_layer) * lr
        hidden_bias -= np.sum(d_hidden_layer,axis=0,keepdims=True) * lr
    return hidden_weights,hidden_bias,output_weights,output_bias,predicted_output

In [2]:
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
expected_output = np.array([[1],[0],[0],[0]])

hidden_weights,hidden_bias,output_weights,output_bias,predicted_output = mlp(inputs,expected_output)

print("Final hidden weights: ",end='')
print(*hidden_weights)
print("Final hidden bias: ",end='')
print(*hidden_bias)
print("Final output weights: ",end='')
print(*output_weights)
print("Final output bias: ",end='')
print(*output_bias)

print("\nOutput from neural network after 400 epochs: ")
print(np.around(predicted_output).astype(int))

Initial hidden weights: [0.51634344 0.51280974] [0.3007779  0.85438774]
Initial hidden biases: [-0.85705951 -0.75600401]
Initial output weights: [0.1507766] [0.87669419]
Initial output biases: [-0.34728655]
Iteration: 0
[[-0.50556116]
 [ 0.54178991]
 [ 0.52515077]
 [ 0.57319068]]
Iteration: 100
[[-0.74638156]
 [ 0.24182163]
 [ 0.23560767]
 [ 0.2234734 ]]
Iteration: 200
[[-0.69326308]
 [ 0.24906188]
 [ 0.24177224]
 [ 0.1953604 ]]
Iteration: 300
[[-0.5798947 ]
 [ 0.24702052]
 [ 0.2406773 ]
 [ 0.15038761]]
Final hidden weights: [2.22474353 0.70412473] [2.09825645 1.05861972]
Final hidden bias: [-1.2724541  -0.95137228]
Final output weights: [-2.90772206] [-0.78383723]
Final output bias: [1.11863957]

Output from neural network after 400 epochs: 
[[1]
 [0]
 [0]
 [0]]
