In [1]:
import numpy as np 
import pandas as pd 
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [2]:
df = pd.read_csv('mnist.csv')
df.head()

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      5    0    0    0    0    0    0    0    0    0  ...      0      0   
1      0    0    0    0    0    0    0    0    0    0  ...      0      0   
2      4    0    0    0    0    0    0    0    0    0  ...      0      0   
3      1    0    0    0    0    0    0    0    0    0  ...      0      0   
4      9    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [3]:
X = []
y = []
for row in df.iterrows() :
    label = row[1][0] #label (the number visible in the image)
    image = list(row[1][1:]) #image information as list, without label
    image = np.array(image) / 255
    X.append(image)
    y.append(label)

X = np.array(X)
y = np.array(y)
print(len(X))
print(len(y))

60000
60000


In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
print(len(X_train), len(y_train))
print(X_train[1].shape)

48000 48000
(784,)


In [5]:
KNN_Classifier = KNeighborsClassifier(n_neighbors = 12, p = 2, metric='minkowski')

In [6]:
KNN_Classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=12)

In [7]:
y_pred = KNN_Classifier.predict(X_test)

In [8]:
acc = accuracy_score(y_test, y_pred)
print("KNN Model Accuracy:", acc)

KNN Model Accuracy: 0.9648333333333333


In [12]:
cm = confusion_matrix(y_test, y_pred)
print("KNN Model Confusion Matrix:\n", cm)

KNN Model Confusion Matrix:
 [[1165    0    3    0    1    2    3    1    0    0]
 [   0 1316    2    0    0    0    0    3    0    1]
 [  10   21 1113    2    2    3    1   19    2    1]
 [   1    1    8 1171    0   11    1    8    7   11]
 [   0    9    0    1 1135    0    4    1    0   26]
 [   5    6    0   17    2 1062    7    0    2    3]
 [   4    4    1    0    1    4 1163    0    0    0]
 [   1   29    2    0    3    0    0 1256    1    7]
 [   3   16    4   26   12   27    3    5 1057    7]
 [   5    3    1    8   12    4    1   20    0 1140]]


In [13]:
cr = classification_report(y_test, y_pred)
print("KNN Model Classification Report:\n", cr)

KNN Model Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.99      0.98      1175
           1       0.94      1.00      0.97      1322
           2       0.98      0.95      0.96      1174
           3       0.96      0.96      0.96      1219
           4       0.97      0.97      0.97      1176
           5       0.95      0.96      0.96      1104
           6       0.98      0.99      0.99      1177
           7       0.96      0.97      0.96      1299
           8       0.99      0.91      0.95      1160
           9       0.95      0.95      0.95      1194

    accuracy                           0.96     12000
   macro avg       0.97      0.96      0.96     12000
weighted avg       0.97      0.96      0.96     12000

