In [1]:
import numpy as np
import numpy.random as ra
import sklearn.datasets as da
import pandas as pd
from sklearn.cluster import KMeans

In [2]:
def rbf_train(input_vector,output_vector,lr,hnum,iter_num):
    weights1 = np.array(np.random.rand(len(input_vector[0]),hnum))
    weights2 = np.array(np.random.rand(hnum+1,len(output_vector[0])))
    
    w=KMeans(n_clusters=hnum).fit(input_vector)
    weights1= np.transpose(w.cluster_centers_)    
    
    print(weights1)
    l=np.zeros((len(input_vector),hnum+1))
    d = (input_vector.max(axis=0)-input_vector.min(axis=0)).max()
    sigma = d/np.sqrt(2*hnum)  
    for i in range(hnum):
        l[:,i] = np.exp(-np.sum((input_vector-np.ones((1,len(input_vector[0])))*weights1[:,i])**2,axis=1)/(2*sigma**2))
    l[:,:-1] /= np.transpose(np.ones((1,len(l)))*l[:,:-1].sum(axis=1))
    print(l)
    l=np.insert(l,0,-1,axis=1)
    weights2=np.dot(np.linalg.pinv(l),output_vector)
    print(weights2)
    return weights1,weights2,sigma
        

In [3]:
def predict(inp,w1,w2):
    hidact=np.zeros((len(inp),hnum+1))
    
    
    for i in range(hnum):
        hidact[:,i] = np.exp(-np.sum((inp - np.ones((1,len(inp[0])))*w1[:,i])**2,axis=1)/(2*sigma**2))
    
    hidact=np.insert(hidact,0,-1,axis=1)
    hidact[:,:-1] /= np.transpose(np.ones((1,len(hidact)))*hidact[:,:-1].sum(axis=1))
    out=np.dot(hidact,w2)
    
    output = np.where(out>0,1,0)
    
    return output 
    
    

In [4]:
d = da.load_iris()
input_vector = d['data'][:,:4]
output_vector = np.array(pd.get_dummies(d['target']))
print(input_vector)
print("\n")
print(output_vector)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [5]:
v = np.concatenate((input_vector,output_vector),axis=1)

ra.shuffle(v)

train_in = v[:101,:4]
train_out = v[:101,4:]
test_in = v[101:,:4]
test_out = v[101:,4:]

In [6]:
hnum=15
lr = 0.01
iter_num = 10
w1,w2,sigma=rbf_train(train_in,train_out,lr,hnum,iter_num)
print(sigma)

[[5.47142857 6.47142857 6.7        5.         5.125      5.72857143
  7.66666667 4.65714286 5.94       6.2        6.75       5.65714286
  7.9        7.16666667 6.21428571]
 [3.84285714 2.87142857 2.97142857 2.3        3.45833333 2.88571429
  2.86666667 3.1        2.82       2.3        3.25       2.45714286
  3.8        3.06666667 3.05714286]
 [1.45714286 5.44285714 4.64285714 3.275      1.54166667 4.25714286
  6.53333333 1.35       4.96       4.7        5.6375     3.85714286
  6.4        5.9        4.52857143]
 [0.25714286 1.91428571 1.44285714 1.025      0.3        1.34285714
  2.23333333 0.20714286 1.92       1.45       2.2875     1.12857143
  2.         1.83333333 1.41428571]]
[[1.68149006e-03 7.55767801e-02 1.36087515e-01 ... 3.12599963e-02
  1.55058512e-01 0.00000000e+00]
 [2.08632962e-06 1.43097428e-01 7.43973947e-02 ... 1.83340176e-01
  4.90717908e-02 0.00000000e+00]
 [2.19855849e-01 2.91058572e-05 4.19280533e-04 ... 1.71038732e-06
  1.28234484e-03 0.00000000e+00]
 ...
 [9.87911

In [7]:
y=predict(test_in,w1,w2)
a=[]
for i in range(len(y)):
    a.append(((y[i]==test_out[i]).sum()==3))
print(np.array(a).sum()/len(y))

0.9183673469387755


In [8]:
c = pd.DataFrame(np.concatenate((y,test_out),axis=1))
c

0    1    2    3    4    5
0   0.0  0.0  1.0  0.0  0.0  1.0
1   0.0  1.0  0.0  0.0  1.0  0.0
2   1.0  0.0  0.0  1.0  0.0  0.0
3   1.0  0.0  0.0  1.0  0.0  0.0
4   0.0  1.0  0.0  0.0  1.0  0.0
5   0.0  0.0  1.0  0.0  0.0  1.0
6   0.0  1.0  1.0  0.0  0.0  1.0
7   1.0  0.0  0.0  1.0  0.0  0.0
8   1.0  0.0  0.0  1.0  0.0  0.0
9   1.0  0.0  0.0  1.0  0.0  0.0
10  0.0  1.0  0.0  0.0  1.0  0.0
11  1.0  0.0  0.0  1.0  0.0  0.0
12  0.0  1.0  0.0  0.0  1.0  0.0
13  0.0  1.0  0.0  0.0  1.0  0.0
14  0.0  1.0  0.0  0.0  1.0  0.0
15  0.0  0.0  1.0  0.0  0.0  1.0
16  0.0  0.0  1.0  0.0  1.0  0.0
17  0.0  0.0  1.0  0.0  0.0  1.0
18  0.0  0.0  1.0  0.0  0.0  1.0
19  1.0  0.0  0.0  1.0  0.0  0.0
20  1.0  0.0  0.0  1.0  0.0  0.0
21  0.0  1.0  0.0  0.0  1.0  0.0
22  0.0  1.0  0.0  0.0  1.0  0.0
23  1.0  0.0  0.0  1.0  0.0  0.0
24  0.0  1.0  0.0  0.0  1.0  0.0
25  0.0  0.0  1.0  0.0  0.0  1.0
26  0.0  0.0  1.0  0.0  0.0  1.0
27  1.0  0.0  0.0  1.0  0.0  0.0
28  0.0  0.0  1.0  0.0  0.0  1.0
29  0.0  1.0  1.0  0.0  0.0  1.0
30  0.0  0.0  1.0  0.0  0.0  1.0
31  0.0  0.0  1.0  0.0  0.0  1.0
32  0.0  1.0  0.0  0.0  1.0  0.0
33  1.0  0.0  0.0  1.0  0.0  0.0
34  0.0  0.0  1.0  0.0  0.0  1.0
35  1.0  0.0  0.0  1.0  0.0  0.0
36  1.0  0.0  0.0  1.0  0.0  0.0
37  0.0  0.0  1.0  0.0  0.0  1.0
38  0.0  0.0  1.0  0.0  0.0  1.0
39  1.0  0.0  0.0  1.0  0.0  0.0
40  0.0  1.0  0.0  0.0  1.0  0.0
41  1.0  0.0  0.0  1.0  0.0  0.0
42  0.0  0.0  1.0  0.0  0.0  1.0
43  0.0  1.0  1.0  0.0  0.0  1.0
44  1.0  0.0  0.0  1.0  0.0  0.0
45  0.0  0.0  1.0  0.0  0.0  1.0
46  1.0  0.0  0.0  1.0  0.0  0.0
47  0.0  1.0  0.0  0.0  1.0  0.0
48  0.0  1.0  0.0  0.0  1.0  0.0

In [9]:
output_vector

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,